"""
Django settings for raktakosh project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env files
from dotenv import load_dotenv
load_dotenv(BASE_DIR.parent / '.env')  # Loads from the root workspace directory
load_dotenv(BASE_DIR / '.env')         # Loads from django-backend directory if present


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-13@#hr6=0l^an*ct881$n4b4nnp%pcdx25!e0(7_7vs()mbtt3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'raktakosh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'raktakosh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os
import dj_database_url
from urllib.parse import urlparse, urlunparse, parse_qs, urlencode

db_url = os.environ.get('DATABASE_URL')
db_user = os.environ.get('DB_USERNAME', 'neondb_owner')
db_password = os.environ.get('DB_PASSWORD', 'npg_wngBJRcV21QO')

if not db_url:
    db_url = 'postgres://ep-royal-salad-a91pt5xf-pooler.gwc.azure.neon.tech/neondb?sslmode=require'

if db_url.startswith('jdbc:'):
    db_url = db_url[5:]

if db_url.startswith('postgresql://'):
    db_url = db_url.replace('postgresql://', 'postgres://')

parsed = urlparse(db_url)

# Sanitize query parameters to strip out channelBinding which breaks psycopg2
query_params = parse_qs(parsed.query)
query_params.pop('channelBinding', None)
query_params.pop('channelbinding', None)
sanitized_query = urlencode(query_params, doseq=True)

netloc = parsed.netloc
if not parsed.username and db_user:
    netloc = f"{db_user}:{db_password}@{parsed.hostname}"
    if parsed.port:
        netloc += f":{parsed.port}"

db_url = urlunparse((
    parsed.scheme if parsed.scheme else 'postgres',
    netloc,
    parsed.path,
    parsed.params,
    sanitized_query,
    parsed.fragment
))

import sys
TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test'

if TESTING:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': dj_database_url.parse(
            db_url,
            conn_max_age=600,
            ssl_require=True
        )
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
