# Generated by Django 5.2.14 on 2026-06-03 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('type', models.CharField(db_column='bloodtype', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Blood',
                'db_table': 'blood',
            },
        ),
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('blood_bank_id', models.AutoField(db_column='blood_bank_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image_url', models.CharField(blank=True, db_column='image_url', max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'blood_bank',
            },
        ),
        migrations.CreateModel(
            name='BloodAndBloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('blood', models.ForeignKey(db_column='bloodtype', on_delete=django.db.models.deletion.CASCADE, to='api.blood')),
                ('blood_bank', models.ForeignKey(db_column='bloodbankid', on_delete=django.db.models.deletion.CASCADE, to='api.bloodbank')),
            ],
            options={
                'db_table': 'blood_and_blood_bank',
                'unique_together': {('blood_bank', 'blood')},
            },
        ),
    ]
