# Generated by Django 5.2.14 on 2026-06-03 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('request_id', models.AutoField(db_column='request_id', primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('quantity_needed', models.IntegerField()),
                ('hospital_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=50)),
                ('urgency_level', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Critical', 'Critical')], default='Normal', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_type', models.ForeignKey(db_column='bloodtype', on_delete=django.db.models.deletion.CASCADE, to='api.blood')),
            ],
            options={
                'db_table': 'blood_request',
            },
        ),
    ]
